import 'package:flutter/material.dart';

// Konstante Registry aller wählbaren Icons
const Map<String, IconData> kIconRegistry = {
  'work': Icons.work,
  'fitness_center': Icons.fitness_center,
  'school': Icons.school,
  'home': Icons.home,
  'book': Icons.book,
  'timer': Icons.timer,
  'brush': Icons.brush,
  'music_note': Icons.music_note,
  'shopping_cart': Icons.shopping_cart,
  'code': Icons.code,
  'alarm': Icons.alarm,
  'pets': Icons.pets,
  'coffee': Icons.coffee,
  'local_cafe': Icons.local_cafe,
  'restaurant': Icons.restaurant,
  'fastfood': Icons.fastfood,
  'shopping_bag': Icons.shopping_bag,
  'flight': Icons.flight,
  'train': Icons.train,
  'directions_walk': Icons.directions_walk,
  'directions_bike': Icons.directions_bike,
  'directions_car': Icons.directions_car,
  'sports_soccer': Icons.sports_soccer,
  'sports_basketball': Icons.sports_basketball,
  'sports_tennis': Icons.sports_tennis,
  'sports_esports': Icons.sports_esports,
  'self_improvement': Icons.self_improvement,
  'medication': Icons.medication,
  'health_and_safety': Icons.health_and_safety,
  'hotel': Icons.hotel,
  'movie': Icons.movie,
  'tv': Icons.tv,
  'language': Icons.language,
  'travel_explore': Icons.travel_explore,
  'eco': Icons.eco,
  'yard': Icons.yard,
  'build': Icons.build,
  'local_hospital': Icons.local_hospital,
  'science': Icons.science,
  'palette': Icons.palette,
  'phone_iphone': Icons.phone_iphone,
  'computer': Icons.computer,
  // Fallback/sonstige
  'category': Icons.category,
};

// Liste der auswählbaren Keys (ohne Fallback)
const List<String> kSelectableIconKeys = [
  'work',
  'fitness_center',
  'school',
  'home',
  'book',
  'timer',
  'brush',
  'music_note',
  'shopping_cart',
  'code',
  'alarm',
  'pets',
  'coffee',
  'local_cafe',
  'restaurant',
  'fastfood',
  'shopping_bag',
  'flight',
  'train',
  'directions_walk',
  'directions_bike',
  'directions_car',
  'sports_soccer',
  'sports_basketball',
  'sports_tennis',
  'sports_esports',
  'self_improvement',
  'medication',
  'health_and_safety',
  'hotel',
  'movie',
  'tv',
  'language',
  'travel_explore',
  'eco',
  'yard',
  'build',
  'local_hospital',
  'science',
  'palette',
  'phone_iphone',
  'computer',
];

IconData iconFromKey(String? key) => kIconRegistry[key] ?? Icons.category;

String keyFromCodePoint(int codePoint) {
  for (final entry in kIconRegistry.entries) {
    if (entry.value.codePoint == codePoint) return entry.key;
  }
  return 'category';
}
